console.log("Welcome to GIT/GITHUB")
console.log("WELCOME to CI/CD PIPELINES")
console.log("Welcome to JavaScript Programming Language")
console.log("Welcome to Auotomation Testing through PlayWright")
console.log("Enhance Your Automation Skills for Future Perspective")
console.log("Welcome to Typescript Programming Language")
console.log("KAMESH RAJAN is an Automation Architect Engineer")
console.log("KAMESH RAJAN will be an Automation Tester")
console.log("Welcome to GIT/GITHUB projects")
console.log("Keep Learning but slowly and gradually")
console.log("Complete this GIT/GITHUB today Anyhow")
console.log("Kamesh REVISE OOPS CONCEPTS TOO")
consol.log("Kamesh We Will do with command prompt also so lets do it now")
